project_id = "diclwatocrixibjpajuf"

[auth]
enabled = true
site_url = "https://jengabiz.africa"
additional_redirect_urls = ["https://jengabiz.africa/auth", "https://jengabiz.africa/reset-password"]

[auth.email]
enable_confirmations = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-signup-confirmation]
verify_jwt = false